#!/bin/sh
#
# Update the bundled scripts config.guess and config.sub
# for the Fast Light Tool Kit (FLTK).
#
# Copyright 1998-2023 by Bill Spitzak and others.
#
# This library is free software. Distribution and use rights are outlined in
# the file "COPYING" which should have been included with this file.  If this
# file is missing or damaged, see the license at:
#
#      https://www.fltk.org/COPYING.php
#
# Please see the following page on how to report bugs and issues:
#
#      https://www.fltk.org/bugs.php
#

#
# Notes to developers:
#
# This script uses wget to download the scripts to the current working
# directory, and it overwrites existing files. You may also use your
# browser to view and download the files if wget is not installed on
# your system.
#
# After downloading the scripts, copy config.guess and config.sub to
# the FLTK root directory, test, and eventually commit the changes:
#
# # cd to FLTK root directory
#
# $ make distclean
# $ autoconf -f
# $ ./configure [options ...]
# $ make
# # test
# $ git add config.guess config.sub
# $ git commit
#

for FILE in config.guess config.sub; do
  echo ""
  echo "Downloading $FILE..."
  echo ""
  wget -O $FILE \
    "https://git.savannah.gnu.org/cgit/config.git/plain/$FILE"
done

echo ""
echo "Download complete, please check for errors, test, and commit changes."
echo ""
