// generated by Fast Light User Interface Designer (fluid) version 0.99
#include "keyboard_ui.h"

Fl_Window *make_window() {
 Fl_Window *w;
 {Fl_Window* o = new Fl_Window(494, 193);
  w = o;
 }
 {Fl_Button* o = new Fl_Button(15, 50, 20, 20, "Esc");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Escape));
 }
 {Fl_Button* o = new Fl_Button(50, 50, 20, 20, "F1");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+1));
 }
 {Fl_Button* o = new Fl_Button(70, 50, 20, 20, "F2");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+2));
 }
 {Fl_Button* o = new Fl_Button(90, 50, 20, 20, "F3");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+3));
 }
 {Fl_Button* o = new Fl_Button(110, 50, 20, 20, "F4");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+4));
 }
 {Fl_Button* o = new Fl_Button(140, 50, 20, 20, "F5");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+5));
 }
 {Fl_Button* o = new Fl_Button(160, 50, 20, 20, "F6");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+6));
 }
 {Fl_Button* o = new Fl_Button(180, 50, 20, 20, "F7");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+7));
 }
 {Fl_Button* o = new Fl_Button(200, 50, 20, 20, "F8");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+8));
 }
 {Fl_Button* o = new Fl_Button(230, 50, 20, 20, "F9");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+9));
 }
 {Fl_Button* o = new Fl_Button(250, 50, 20, 20, "F10");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+10));
 }
 {Fl_Button* o = new Fl_Button(270, 50, 20, 20, "F11");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+11));
 }
 {Fl_Button* o = new Fl_Button(290, 50, 20, 20, "F12");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_F+12));
 }
 {Fl_Button* o = new Fl_Button(325, 50, 20, 20, "Print");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Print));
 }
 {Fl_Button* o = new Fl_Button(345, 50, 20, 20, "Sclk");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Scroll_Lock));
 }
 {Fl_Button* o = new Fl_Button(365, 50, 20, 20, "Paus");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Pause));
 }
 {Fl_Button* o = new Fl_Button(15, 80, 20, 20, "`");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(35, 80, 20, 20, "1");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(55, 80, 20, 20, "2");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(75, 80, 20, 20, "3");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(95, 80, 20, 20, "4");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(115, 80, 20, 20, "5");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(135, 80, 20, 20, "6");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(155, 80, 20, 20, "7");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(175, 80, 20, 20, "8");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(195, 80, 20, 20, "9");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(215, 80, 20, 20, "0");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(235, 80, 20, 20, "-");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(255, 80, 20, 20, "=");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(275, 80, 35, 20, "Bksp");
  o->labeltype(FL_SYMBOL_LABEL);
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_BackSpace));
 }
 {Fl_Button* o = new Fl_Button(325, 80, 20, 20, "Ins");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Insert));
 }
 {Fl_Button* o = new Fl_Button(345, 80, 20, 20, "Home");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Home));
 }
 {Fl_Button* o = new Fl_Button(365, 80, 20, 20, "pgup");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Page_Up));
 }
 {Fl_Button* o = new Fl_Button(400, 80, 20, 20, "Num");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Num_Lock));
 }
 {Fl_Button* o = new Fl_Button(420, 80, 20, 20, "/");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'/'));
 }
 {Fl_Button* o = new Fl_Button(440, 80, 20, 20, "*");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'*'));
 }
 {Fl_Button* o = new Fl_Button(460, 80, 20, 20, "-");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'-'));
 }
 {Fl_Button* o = new Fl_Button(15, 100, 27, 20, "Tab");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Tab));
 }
 {Fl_Button* o = new Fl_Button(42, 100, 20, 20, "Q");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(62, 100, 20, 20, "W");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(82, 100, 20, 20, "E");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(102, 100, 20, 20, "R");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(122, 100, 20, 20, "T");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(142, 100, 20, 20, "Y");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(162, 100, 20, 20, "U");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(182, 100, 20, 20, "I");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(202, 100, 20, 20, "O");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(222, 100, 20, 20, "P");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(242, 100, 20, 20, "[");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(262, 100, 20, 20, "]");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(282, 100, 28, 20, "\\");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)('|'));
  o->align(20);
 }
 {Fl_Button* o = new Fl_Button(325, 100, 20, 20, "Del");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Delete));
 }
 {Fl_Button* o = new Fl_Button(345, 100, 20, 20, "End");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_End));
 }
 {Fl_Button* o = new Fl_Button(365, 100, 20, 20, "pgdn");
  o->labelsize(8);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Page_Down));
 }
 {Fl_Button* o = new Fl_Button(400, 100, 20, 20, "7");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'7'));
 }
 {Fl_Button* o = new Fl_Button(420, 100, 20, 20, "8");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'8'));
 }
 {Fl_Button* o = new Fl_Button(440, 100, 20, 20, "9");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'9'));
 }
 {Fl_Button* o = new Fl_Button(460, 100, 20, 40, "+");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'+'));
  o->align(17);
 }
 {Fl_Button* o = new Fl_Button(15, 120, 36, 20, "Lock");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Caps_Lock));
 }
 {Fl_Button* o = new Fl_Button(51, 120, 20, 20, "A");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(71, 120, 20, 20, "S");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(91, 120, 20, 20, "D");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(111, 120, 20, 20, "F");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(131, 120, 20, 20, "G");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(151, 120, 20, 20, "H");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(171, 120, 20, 20, "J");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(191, 120, 20, 20, "K");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(211, 120, 20, 20, "L");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(231, 120, 20, 20, ";");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(251, 120, 20, 20, "\'");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(271, 120, 39, 20, "Enter");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Enter));
 }
 {Fl_Button* o = new Fl_Button(400, 120, 20, 20, "4");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'4'));
 }
 {Fl_Button* o = new Fl_Button(420, 120, 20, 20, "5");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'5'));
 }
 {Fl_Button* o = new Fl_Button(440, 120, 20, 20, "6");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'6'));
 }
 {Fl_Button* o = new Fl_Button(15, 140, 45, 20, "Shift");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Shift_L));
 }
 {Fl_Button* o = new Fl_Button(60, 140, 20, 20, "Z");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(80, 140, 20, 20, "X");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(100, 140, 20, 20, "C");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(120, 140, 20, 20, "V");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(140, 140, 20, 20, "B");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(160, 140, 20, 20, "N");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(180, 140, 20, 20, "M");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(200, 140, 20, 20, ",");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(220, 140, 20, 20, ".");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(240, 140, 20, 20, "/");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb);
 }
 {Fl_Button* o = new Fl_Button(260, 140, 50, 20, "Shift");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Shift_R));
 }
 {Fl_Button* o = new Fl_Button(345, 140, 20, 20, "@8->");
  o->labeltype(FL_SYMBOL_LABEL);
  o->labelsize(10);
  o->labelcolor(47);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Up));
 }
 {Fl_Button* o = new Fl_Button(400, 140, 20, 20, "1");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'1'));
 }
 {Fl_Button* o = new Fl_Button(420, 140, 20, 20, "2");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'2'));
 }
 {Fl_Button* o = new Fl_Button(440, 140, 20, 20, "3");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'3'));
 }
 {Fl_Button* o = new Fl_Button(460, 140, 20, 40);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP_Enter));
 }
 {Fl_Button* o = new Fl_Button(15, 160, 30, 20, "Ctrl");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Control_L));
 }
 {Fl_Button* o = new Fl_Button(45, 160, 30, 20, "Meta");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Meta_L));
 }
 {Fl_Button* o = new Fl_Button(75, 160, 30, 20, "Alt");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Alt_L));
 }
 {Fl_Button* o = new Fl_Button(105, 160, 85, 20);
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(' '));
 }
 {Fl_Button* o = new Fl_Button(190, 160, 30, 20, "Alt");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Alt_R));
 }
 {Fl_Button* o = new Fl_Button(220, 160, 30, 20, "Meta");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Meta_R));
 }
 {Fl_Button* o = new Fl_Button(250, 160, 30, 20, "Menu");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Menu));
 }
 {Fl_Button* o = new Fl_Button(280, 160, 30, 20, "Ctrl");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Control_R));
 }
 {Fl_Button* o = new Fl_Button(325, 160, 20, 20, "@4->");
  o->labeltype(FL_SYMBOL_LABEL);
  o->labelsize(10);
  o->labelcolor(47);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Left));
 }
 {Fl_Button* o = new Fl_Button(345, 160, 20, 20, "@2->");
  o->labeltype(FL_SYMBOL_LABEL);
  o->labelsize(10);
  o->labelcolor(47);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Down));
 }
 {Fl_Button* o = new Fl_Button(365, 160, 20, 20, "@6->");
  o->labeltype(FL_SYMBOL_LABEL);
  o->labelsize(10);
  o->labelcolor(47);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_Right));
 }
 {Fl_Button* o = new Fl_Button(400, 160, 40, 20, "0");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'0'));
  o->align(20);
 }
 {Fl_Button* o = new Fl_Button(440, 160, 20, 20, ".");
  o->labelsize(10);
  o->callback((Fl_Callback*)key_cb, (void*)(FL_KP+'.'));
 }
 {Fl_Input* o = new Fl_Input(15, 10, 370, 30);
 }
 {Fl_Button* o = new Fl_Button(400, 5, 20, 10, "shift");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_SHIFT));
 }
 {Fl_Button* o = new Fl_Button(420, 5, 20, 10, "lock");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_CAPS_LOCK));
 }
 {Fl_Button* o = new Fl_Button(440, 5, 20, 10, "ctrl");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_CTRL));
 }
 {Fl_Button* o = new Fl_Button(460, 5, 20, 10, "alt");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_ALT));
 }
 {Fl_Button* o = new Fl_Button(440, 15, 20, 10, "meta");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_META));
 }
 {Fl_Button* o = new Fl_Button(420, 15, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x20));
 }
 {Fl_Button* o = new Fl_Button(400, 15, 20, 10, "num");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_NUM_LOCK));
 }
 {Fl_Button* o = new Fl_Button(400, 25, 20, 10, "b1");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_BUTTON1));
 }
 {Fl_Button* o = new Fl_Button(420, 25, 20, 10, "b2");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_BUTTON2));
 }
 {Fl_Button* o = new Fl_Button(440, 25, 20, 10, "b3");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_BUTTON3));
 }
 {Fl_Button* o = new Fl_Button(460, 15, 20, 10, "sclk");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(FL_SCROLL_LOCK));
 }
 {Fl_Button* o = new Fl_Button(460, 25, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x800));
 }
 {Fl_Button* o = new Fl_Button(400, 35, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x1000));
 }
 {Fl_Button* o = new Fl_Button(420, 35, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x2000));
 }
 {Fl_Button* o = new Fl_Button(440, 35, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x4000));
 }
 {Fl_Button* o = new Fl_Button(460, 35, 20, 10, "?");
  o->box(FL_THIN_UP_BOX);
  o->color2(3);
  o->labelsize(8);
  o->callback((Fl_Callback*)shift_cb, (void*)(0x8000));
 }
 w->end();
 return w;
}
