In the ms subdirectory, you'll find an old vc .net 2003 project dir called vcnet.
VC .net 2003 users can build the full distrib from the ide/visualc project dir 
which is still supported and should be up-to-date.

If we find a contributor capable of maintaining this ide distrib, we'll
be happy to update it and move it back to the ide subdir.

Note: the vcnet project subdir was originally located on the root directory.
