#!/bin/tcsh
# I use tcsh to get the better glob matching.  Wish there were a more
# portable way...
# argument to this script is the version number or word like "BETA"

if ( $1 == "" ) then
echo "Version number needed"
exit 1
endif

set f="fltk-$1"
rm -f $f
ln -s . $f

echo "Making $f.tgz"
tar -cf \
	$f.tar $f/README $f/COPYING $f/version $f/Makefile \
	$f/configure $f/*.in $f/makefiles/* $f/makedist $f/install-sh \
	$f/{src,fluid,FL,test,GL}/{README,Makefile,*.{fl,[CHch],x?m,menu}} \
	$f/documentation/*.{html,gif,jpg} $f/documentation/CHANGES \
	$f/forms.h $f/win32/* $f/lib/... \

gzip -f $f.tar
mv $f.tar.gz $f.tgz

rm -f $f
