//
// Loading TrueType fonts from files and from memory with Fl::load_font().
//
// Copyright 2026 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Native_File_Chooser.H>
#include <FL/fl_ask.H>

// The regular style of the "FLTK Pixel" font, compiled into the application.
// Generated by fonts/make_fltk_pixel.py, you can also use a FLUID Data node.
#include "fonts/FLTKPixel.h"

// The other styles are loaded from files in this directory. CMake sets it to
// the absolute path of examples/fonts, so the demo runs from any directory.
#ifndef FONT_DIR
#  define FONT_DIR "fonts"
#endif

static const char *sample = "The quick brown fox jumps over the lazy dog";

// Load the four styles into consecutive font numbers, so that
// FL_PIXEL + FL_BOLD etc. work like FL_HELVETICA + FL_BOLD
static const Fl_Font FL_PIXEL = FL_FREE_FONT;
static const Fl_Font FL_CUSTOM = FL_FREE_FONT + 4;

static Fl_Box *custom_box = NULL;

// Shows the sample text in `font` if it was loaded, or an error message
static void add_sample(int y, const char *title, Fl_Font font, bool loaded) {
  Fl_Box *label = new Fl_Box(10, y, 170, 40, title);
  label->align(FL_ALIGN_INSIDE | FL_ALIGN_RIGHT);
  Fl_Box *text = new Fl_Box(190, y, 600, 40);
  text->align(FL_ALIGN_INSIDE | FL_ALIGN_LEFT);
  if (loaded) {
    text->label(sample);
    text->labelfont(font);
    text->labelsize(20); // 2 screen pixels per font pixel
  } else {
    text->label("(could not load the font)");
    text->labelcolor(FL_RED);
  }
}

// Lets the user try any font file
static void load_cb(Fl_Widget *, void *) {
  Fl_Native_File_Chooser chooser;
  chooser.title("Load a Font File");
  chooser.filter("TrueType and OpenType Fonts\t*.{ttf,otf,ttc}");
  if (chooser.show() != 0) return;
  if (Fl::load_font(FL_CUSTOM, chooser.filename()) < 0) {
    fl_alert("Could not load the font file\n%s", chooser.filename());
    return;
  }
  custom_box->label(sample);
  custom_box->labelfont(FL_CUSTOM);
  custom_box->labelcolor(FL_FOREGROUND_COLOR);
  custom_box->window()->redraw();
}

int main(int argc, char **argv) {
  // Load a font from memory, the data is copied by FLTK
  bool regular = Fl::load_font(FL_PIXEL, fltk_pixel_regular_ttf,
                               sizeof(fltk_pixel_regular_ttf)) >= 0;
  // Load fonts from files
  bool bold = Fl::load_font(FL_PIXEL + FL_BOLD, FONT_DIR "/FLTKPixel-Bold.ttf") >= 0;
  bool italic = Fl::load_font(FL_PIXEL + FL_ITALIC, FONT_DIR "/FLTKPixel-Italic.ttf") >= 0;
  bool bold_italic = Fl::load_font(FL_PIXEL + FL_BOLD_ITALIC,
                                   FONT_DIR "/FLTKPixel-BoldItalic.ttf") >= 0;

  Fl_Double_Window *win = new Fl_Double_Window(800, 290, "Fl::load_font()");
  add_sample(10, "Regular, from memory:", FL_PIXEL, regular);
  add_sample(50, "Bold, from file:", FL_PIXEL + FL_BOLD, bold);
  add_sample(90, "Italic, from file:", FL_PIXEL + FL_ITALIC, italic);
  add_sample(130, "Bold Italic, from file:", FL_PIXEL + FL_BOLD_ITALIC, bold_italic);

  Fl_Button *button = new Fl_Button(20, 190, 160, 30, "Load Font File...");
  button->callback(load_cb);
  custom_box = new Fl_Box(190, 185, 600, 40, "(choose a .ttf, .otf, or .ttc file)");
  custom_box->align(FL_ALIGN_INSIDE | FL_ALIGN_LEFT);
  custom_box->labelsize(20);
  custom_box->labelcolor(FL_INACTIVE_COLOR);

  Fl_Box *note = new Fl_Box(20, 240, 770, 40,
    "Fonts loaded with Fl::load_font() are only visible to this application.");
  note->align(FL_ALIGN_INSIDE | FL_ALIGN_LEFT);
  note->labelsize(12);
  win->end();
  win->show(argc, argv);
  return Fl::run();
}
