.TH fltk 1 "Fast Light Tool Kit" "27 January 2001"
.SH NAME
fltk \- the fast light Tool Kit
.sp
.SH SYNOPSIS

The Fast Light Tool Kit ("FLTK", pronounced "fulltick") is a LGPL'd
C++ graphical user interface toolkit for X (UNIX(R)), OpenGL(R), and
Microsoft(R) Windows(R) NT 4.0, 95, or 98. It was originally developed
by Mr. Bill Spitzak and is currently maintained by a small group of
developers across the world with a central repository in the US.

.SH SEE ALSO
.nf
FLTK Programming Manual
file:/usr/local/share/doc/fltk/index.html
.PP
http://www.fltk.org
.PP
.BR fluid (1)
.SH AUTHOR
Bill Spitzak and others.
