#
# This script builds the FLUID User Handbook as html directory and pdf
# document on a Linux machine.
#

name: 'Build FLUID User Handbook'

# This job must be called explicitly form the 'Actions' tab in GitHub
on: push

#on:
#  workflow_dispatch:
#    inputs:
#      build-pdf:
#        type: boolean
#        description: Build pdf file as well
#        default: 'true'

permissions:
  contents: read

jobs:
  build-html:
    runs-on: macos-latest

#    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        brew install doxygen
        brew install --cask basictex
        eval "$(/usr/libexec/path_helper)"

#        sudo apt-get update -y
#        sudo apt-get install -y libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev libpango1.0-dev libgtk-3-dev
#        sudo apt-get install -y doxygen
#        sudo apt-get install -y doxygen-latex

# use the following line when 1.10.0 becomes available on Ubuntu. On 4/14/24 it's 1.9.2
#        sudo apt-get install -y doxygen=1.10.0

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE \
          -D CMAKE_BUILD_TYPE=Debug \
          -D CMAKE_CXX_STANDARD=11 \
          -D CMAKE_CXX_EXTENSIONS=OFF \
          -D CMAKE_C_FLAGS_INIT="-Wall -Wunused" \
          -D CMAKE_CXX_FLAGS_INIT="-Wall -Wunused -Wsuggest-override" \
          -D FLTK_BUILD_FLTK_OPTIONS=OFF \
          -D FLTK_BUILD_FLUID=ON \
          -D FLTK_BUILD_GL=OFF \
          -D FLTK_BUILD_TEST=OFF \
          -D FLTK_BUILD_FLUID_DOCS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config Debug --target fluid_docs
        cmake --build . --config Debug --target fluid_pdf
        ls $GITHUB_WORKSPACE/fluid/documentation
        ls $GITHUB_WORKSPACE/fluid/documentation/html

